### PR TITLE
Fedora fixes

### PR DESCRIPTION
**Pull request by kwizart**
Here are fedora fixes against currently installed system

### CODE REVIEW

**Comment by itamarjp** [comment]
please commit, thank you.

**Comment by kwizart** [comment]
Anyone here can commit the changes ?
This failure is not related to this change.

**Comment by kwizart** [comment]
Ping anyone to fix it ?

**Comment by nlm** [comment]
I'll close this as it seems outdated, don't hesitate to re-open it if needed, thanks

**Pull request closed without merging**
